### ISSUE TITLE
fmi3GetIntervalDecimal is not allowed in Clock.fmu 

### ISSUE THREAD

**Issue by masoud-najafi** [modelica/Reference-FMUs#459]
Hi,
If the importer calls fmi3GetIntervalDecimal to retrieve the IntervalDecimal of 'inClock1' clock, this error message is raised.
" Get Interval is not allowed for value reference 1001."
fmi3GetIntervalDecimal  should be able to return the period and shift of a periodic clock. The same holds for fmi3GetShiftDecimal.
Thanks

**Comment by MBlesken** [comment]
@masoud-najafi I think fmi3GetIntervalDecimal does not need to be implemented for  1001 since it is not allowed to be called for a constant clock: 

State [Clock Activation Mode](https://fmi-standard.org/docs/3.0/#ClockActivationMode) - Allowed functions says "Functions [fmi3GetIntervalDecimal](https://fmi-standard.org/docs/3.0/#fmi3GetIntervalDecimal) and [fmi3GetIntervalFraction](https://fmi-standard.org/docs/3.0/#fmi3GetIntervalFraction)
			These function calls are allowed for [tunable](https://fmi-standard.org/docs/3.0/#tunable-clock) and [changing](https://fmi-standard.org/docs/3.0/#changing-aperiodic-clock) aperiodic Clocks."

State: [Clock Update Mode](https://fmi-standard.org/docs/3.0/#ClockUpdateMode) - Allowed Function "Functions [fmi3GetIntervalDecimal](https://fmi-standard.org/docs/3.0/#fmi3GetIntervalDecimal) & [fmi3GetIntervalFraction](https://fmi-standard.org/docs/3.0/#fmi3GetIntervalFraction)
			These function calls are allowed for [countdown](https://fmi-standard.org/docs/3.0/#countdown-aperiodic-clock) Clocks"

Unfortunately it is a bit misguiding that [5.3. Code Example](https://fmi-standard.org/docs/3.0/#example-scheduled-execution) contains an implementation for fmi3GetIntervalDecimal of a constant clock.

In general it makes sense for the importer to ask for period and shift of aperiodic clocks but not so much for periodic clocks. It can retrieve this information straight from the xml.

**Comment by masoud-najafi** [comment]
HI @MBlesken 
Actually I need to call fmi3GetIntervalDecimal and fmi3GetIntervalFraction in the **initialization** state. I cannot find any restriction about using these APIs in the initialization state. I agree that if the intervalVariability is constant, the interval value can be extracted from the XML. However, reading the textual XML file is susceptible to losing precision. So leaving the possibility of reading the interval value from the C code is always good.
